language: "node_js"
node_js:
  - "0.10"
env:
  - JQUERY_VERSION=1.9.1 EMBER_VERSION=1.0.1 HANDLEBARS_VERSION=1.1.0
  - JQUERY_VERSION=1.11.0 EMBER_VERSION=1.7.1 HANDLEBARS_VERSION=1.3.0
  - JQUERY_VERSION=1.11.0 EMBER_VERSION=1.9.1 HANDLEBARS_VERSION=2.0.0
  - JQUERY_VERSION=1.11.0 EMBER_VERSION=1.10.0 EMBER_TEMPLATE_COMPILER=true HANDLEBARS_VERSION=2.0.0
  - JQUERY_VERSION=2.0.3 EMBER_VERSION=release EMBER_TEMPLATE_COMPILER=true HANDLEBARS_VERSION=2.0.0
  - JQUERY_VERSION=1.11.0 EMBER_VERSION=beta EMBER_TEMPLATE_COMPILER=true HANDLEBARS_VERSION=2.0.0
  - JQUERY_VERSION=1.11.0 EMBER_VERSION=canary EMBER_TEMPLATE_COMPILER=true HANDLEBARS_VERSION=2.0.0
matrix:
  allow_failures:
    - node_js: "0.10"
      env: JQUERY_VERSION=2.0.3 EMBER_VERSION=release EMBER_TEMPLATE_COMPILER=true HANDLEBARS_VERSION=2.0.0
    - node_js: "0.10"
      env: JQUERY_VERSION=1.11.0 EMBER_VERSION=beta EMBER_TEMPLATE_COMPILER=true HANDLEBARS_VERSION=2.0.0
    - node_js: "0.10"
      env: JQUERY_VERSION=1.11.0 EMBER_VERSION=canary EMBER_TEMPLATE_COMPILER=true HANDLEBARS_VERSION=2.0.0
install: make development_dependencies vendor_install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: make jshint test
